//menu
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

//home
export const GET_HOME_DATA_BEGIN = "GET_HOME_DATA_BEGIN";
export const GET_HOME_DATA_SUCCESS = "GET_HOME_DATA_SUCCESS";
export const GET_HOME_DATA_ERROR = "GET_HOME_DATA_ERROR";

// login
export const GET_LOGIN_BEGIN = "GET_LOGIN_BEGIN";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";
export const GET_LOGIN_ERROR = "GET_LOGIN_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const EDIT_USER_DETAILS = "EDIT_USER_DETAILS";

//product
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_SEARCH_PRODUCTS_SUCCESS = "GET_SEARCH_PRODUCTS_SUCCESS";
export const GET_SEARCH_PRODUCTS_ERROR = "GET_SEARCH_PRODUCTS_ERROR";

export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_SELLER_BEGIN = "GET_SELLER_BEGIN";
export const GET_SELLER_SUCCESS = "GET_SELLER_SUCCESS";
export const GET_SELLER_ERROR = "GET_SELLER_ERROR";

export const GET_MANUFACTURE_BEGIN = "GET_MANUFACTURE_BEGIN";
export const GET_MANUFACTURE_SUCCESS = "GET_MANUFACTURE_SUCCESS";
export const GET_MANUFACTURE_ERROR = "GET_MANUFACTURE_ERROR";

export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

// cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const INCREASE_CART_QTY = "INCREASE_CART_QTY";
export const DECREASE_CART_QTY = "DECREASE_CART_QTY";
export const RESTORE_TOTAL = "RESTORE_TOTAL";
export const RESTORE_QTY = "RESTORE_QTY";
export const SET_USER_QTY = "SET_USER_QTY";

// checkout
export const PLACE_ORDER_BEGIN = "PLACE_ORDER_BEGIN";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_ERROR = "PLACE_ORDER_ERROR";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_SINGLE_ORDER_DETILS = "GET_SINGLE_ORDER_DETILS";
export const RETURN_ORDER = "RETURN_ORDER";
export const RE_ORDER_PRODUCT = "RE_ORDER_PRODUCT";
export const DOWNLOAD_INVOICE = "DOWNLOAD_INVOICE";
export const STORE_TICKERS_LIST = "STORE_TICKERS_LIST";

export const GET_ADDRESS_BEGIN = "GET_ADDRESS_BEGIN";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";

export const ADD_ADDRESS_BEGIN = "ADD_ADDRESS_BEGIN";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_ERROR = "ADD_ADDRESS_ERROR";

// wallet

export const WALLET_BEGIN = "WALLET_BEGIN";
export const WALLET_SUCCESS = "WALLET_SUCCESS";
export const WALLET_ERROR = "WALLET_ERROR";

// cancel order

export const CANCEL_ORDER_BEGIN = "CANCEL_ORDER_BEGIN";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_ERROR = "CANCEL_ORDER_ERROR";
